exports.getAll = async(req, res, next) => {
    try {

    } catch (err) {
        return functions.setError(res, err.message);
    };
};